# conda env create|update --file environment.yml
name: sdc-rag-backend
dependencies:
  - python=3.12
  - pip
  - pip:
      - python-dotenv
      - streamlit
      - pypdf
      - langchain
      - langchain-community
      - langchain-google-genai 
      - langchain-qdrant
